### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by feistyz** [capnproto/node-capnp#48] opened 2019-06-03 15:31 UTC
Hi,
Seem to be having problems getting node-capnp installed.

Mac OS
Node: v12.3.1
NPM: 6.9.0

I get the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! capnp@0.3.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the capnp@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Looking in the log file:
```
81 warn enoent ENOENT: no such file or directory, open '/Users/XXX/package.json'
82 verbose enoent This is related to npm not being able to find a file.
83 warn XXX No description
84 warn XXX No repository field.
85 warn XXX No README data
86 warn XXX No license field.
87 verbose stack Error: capnp@0.3.1 install: `node ./build.js`
87 verbose stack Exit status 1
87 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
87 verbose stack     at EventEmitter.emit (events.js:200:13)
87 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
87 verbose stack     at ChildProcess.emit (events.js:200:13)
87 verbose stack     at maybeClose (internal/child_process.js:1021:16)
87 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

Any ideas?

**Comment by feistyz** [comment] 2019-06-03 16:04
I realized the error of my ways... I was running it from the wrong directory. Need to be running from my project directory.

However, it is still not working :-( 

Here is the latest error:

```
79 silly saveTree   └── symbol-observable@1.2.0
80 verbose stack Error: capnp@0.3.1 install: `node ./build.js`
80 verbose stack Exit status 1
80 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
80 verbose stack     at EventEmitter.emit (events.js:200:13)
80 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
80 verbose stack     at ChildProcess.emit (events.js:200:13)
80 verbose stack     at maybeClose (internal/child_process.js:1021:16)
80 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
81 verbose pkgid capnp@0.3.1
82 verbose cwd /Users/yuri/dev/flipper-react-native
83 verbose Darwin 17.7.0
84 verbose argv "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/bin/npm" "install" "capnp"
85 verbose node v12.3.1
86 verbose npm  v6.9.0
87 error code ELIFECYCLE
88 error errno 1
89 error capnp@0.3.1 install: `node ./build.js`
89 error Exit status 1
90 error Failed at the capnp@0.3.1 install script.
90 error This is probably not a problem with npm. There is likely additional logging output above.
91 verbose exit [ 1, true ]
```

**Comment by kentonv** [comment] 2019-06-06 05:51
See my Jan 7 comment on #41 -- for node 10 and 12 you'll need to use the `node10` branch, but when I tried to publish to npm, the package ended up broken. I haven't had a chance to investigate, especially since it only seems to fail after the publish. You could try installing from source for now.

**Comment by kentonv** [comment] 2019-06-06 05:52
Closing as dupe of #41.

**Closed as completed by kentonv** 2019-06-06 05:52 UTC
